substitutions:
  _REGION: asia-south1
  _REPO: cloud-run-source-deploy
  _SERVICE: easelegal-00001-vw8
  _IMAGE: asia-south1-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_SERVICE}:$SHORT_SHA

steps:
  # Build the Docker image (looks for Dockerfile inside backend/)
  - name: gcr.io/cloud-builders/docker
    args: ["build", "-t", "${_IMAGE}", "."]
    dir: backend

  # Push the image to Artifact Registry
  - name: gcr.io/cloud-builders/docker
    args: ["push", "${_IMAGE}"]

  # Deploy to Cloud Run
  - name: gcr.io/cloud-builders/gcloud
    args:
      - run
      - deploy
      - ${_SERVICE}
      - --image=${_IMAGE}
      - --region=${_REGION}
      - --platform=managed
      - --allow-unauthenticated
      - --quiet

images:
  - ${_IMAGE}
